Update mkinitcpio -> 38, add cryptheader patch
Previous cryptheader patch for cryptsetup package:
https://github.com/gavinhungry/patches/commit/2576350ba00f872e63985e914608ea40b03dcd55

diff --git a/mkinitcpio/mkinitcpio_cryptheader.patch b/mkinitcpio/mkinitcpio_cryptheader.patch
--- a/mkinitcpio/mkinitcpio_cryptheader.patch
+++ b/mkinitcpio/mkinitcpio_cryptheader.patch
@@ -1,8 +1,8 @@
-diff --color -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
---- cryptsetup.ORIG/hooks-encrypt	2023-03-22 08:51:54.485362292 -0700
-+++ cryptsetup/hooks-encrypt	2023-03-22 08:54:55.917925430 -0700
-@@ -33,6 +33,29 @@
-         [ ! -f ${ckeyfile} ] && echo "Keyfile could not be opened. Reverting to passphrase."
+diff -ru mkinitcpio.ORIG/src/mkinitcpio-38/hooks/encrypt mkinitcpio/src/mkinitcpio-38/hooks/encrypt
+--- mkinitcpio.ORIG/src/mkinitcpio-38/hooks/encrypt	2024-03-04 10:45:44.457249286 -0800
++++ mkinitcpio/src/mkinitcpio-38/hooks/encrypt	2024-03-04 10:45:44.460582676 -0800
+@@ -37,6 +37,29 @@
+         [ ! -f "${ckeyfile}" ] && echo "Keyfile could not be opened. Reverting to passphrase."
      fi
  
 +    # support detached headers
@@ -21,7 +21,7 @@ diff --color -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
 +            umount /cheader
 +        fi
 +
-+        if [ -f ${cheaderfile} ]; then
++        if [ -f "${cheaderfile}" ]; then
 +            cryptargs="${cryptargs} --header ${cheaderfile}"
 +        else
 +            echo "Detached header could not be opened. Ignoring."
@@ -30,17 +30,17 @@ diff --color -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
 +
      if [ -n "${cryptdevice}" ]; then
          DEPRECATED_CRYPT=0
-         IFS=: read cryptdev cryptname cryptoptions <<EOF
-@@ -81,7 +104,7 @@
+         IFS=: read -r cryptdev cryptname cryptoptions <<EOF
+@@ -85,7 +108,7 @@
      unset OLDIFS
  
-     if resolved=$(resolve_device "${cryptdev}" ${rootdelay}); then
--        if cryptsetup isLuks ${resolved} >/dev/null 2>&1; then
-+        if (cryptsetup isLuks ${resolved} >/dev/null 2>&1 || cryptsetup isLuks ${cheaderfile} >/dev/null 2>&1); then
-             [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
+     if resolved=$(resolve_device "${cryptdev}" "${rootdelay}"); then
+-        if cryptsetup isLuks "${resolved}" >/dev/null 2>&1; then
++        if (cryptsetup isLuks "${resolved}" >/dev/null 2>&1 || cryptsetup isLuks "${cheaderfile}" >/dev/null 2>&1); then
+             [ "${DEPRECATED_CRYPT}" -eq 1 ] && warn_deprecated
              dopassphrase=1
              # If keyfile exists, try to use that
-@@ -99,8 +122,7 @@
+@@ -103,8 +126,7 @@
                          --prompt="A password is required to access the ${cryptname} volume" \
                          --command="cryptsetup open --type luks --key-file=- ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}"
                  else
@@ -49,16 +49,16 @@ diff --color -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
 +                    echo -e "\033[2J\033[1;1H"
  
                      #loop until we get a real password
-                     while ! eval cryptsetup open --type luks ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; do
-@@ -157,8 +179,10 @@
+                     while ! eval cryptsetup open --type luks "${resolved}" "${cryptname}" "${cryptargs}" "${CSQUIET}"; do
+@@ -159,8 +181,10 @@
          else
              err "Failed to open encryption mapping: The device ${cryptdev} is not a LUKS volume and the crypto= paramater was not specified."
          fi
 +    else
 +        err "Could not resolve encryption device: ${cryptdev}"
      fi
--    rm -f ${ckeyfile}
-+    rm -f ${ckeyfile} ${cheaderfile}
+-    rm -f "${ckeyfile}"
++    rm -f "${ckeyfile}" "${cheaderfile}"
  }
  
  # vim: set ft=sh ts=4 sw=4 et:
