Update cryptsetup -> 2.6.1

diff --git a/cryptsetup/cryptsetup_cryptheader.patch b/cryptsetup/cryptsetup_cryptheader.patch
--- a/cryptsetup/cryptsetup_cryptheader.patch
+++ b/cryptsetup/cryptsetup_cryptheader.patch
@@ -1,6 +1,6 @@
-diff -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
---- cryptsetup.ORIG/hooks-encrypt	2018-01-07 22:35:04.514626428 -0800
-+++ cryptsetup/hooks-encrypt	2018-01-07 22:35:04.537959293 -0800
+diff --color -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
+--- cryptsetup.ORIG/hooks-encrypt	2023-03-22 08:51:54.485362292 -0700
++++ cryptsetup/hooks-encrypt	2023-03-22 08:54:55.917925430 -0700
 @@ -33,6 +33,29 @@
          [ ! -f ${ckeyfile} ] && echo "Keyfile could not be opened. Reverting to passphrase."
      fi
@@ -31,8 +31,8 @@ diff -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
      if [ -n "${cryptdevice}" ]; then
          DEPRECATED_CRYPT=0
          IFS=: read cryptdev cryptname cryptoptions <<EOF
-@@ -67,7 +90,7 @@
-     done
+@@ -81,7 +104,7 @@
+     unset OLDIFS
  
      if resolved=$(resolve_device "${cryptdev}" ${rootdelay}); then
 -        if cryptsetup isLuks ${resolved} >/dev/null 2>&1; then
@@ -40,18 +40,17 @@ diff -ru cryptsetup.ORIG/hooks-encrypt cryptsetup/hooks-encrypt
              [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
              dopassphrase=1
              # If keyfile exists, try to use that
-@@ -80,9 +103,7 @@
-             fi
-             # Ask for a passphrase
-             if [ ${dopassphrase} -gt 0 ]; then
--                echo ""
--                echo "A password is required to access the ${cryptname} volume:"
--
-+                echo -e "\033[2J\033[1;1H"
-                 #loop until we get a real password
-                 while ! eval cryptsetup open --type luks ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; do
-                     sleep 2;
-@@ -137,8 +158,10 @@
+@@ -99,8 +122,7 @@
+                         --prompt="A password is required to access the ${cryptname} volume" \
+                         --command="cryptsetup open --type luks --key-file=- ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}"
+                 else
+-                    echo ""
+-                    echo "A password is required to access the ${cryptname} volume:"
++                    echo -e "\033[2J\033[1;1H"
+ 
+                     #loop until we get a real password
+                     while ! eval cryptsetup open --type luks ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; do
+@@ -157,8 +179,10 @@
          else
              err "Failed to open encryption mapping: The device ${cryptdev} is not a LUKS volume and the crypto= paramater was not specified."
          fi
